import net from "node:net";
import { spawn } from "node:child_process";
import { existsSync, statSync, unlinkSync } from "node:fs";
import path from "node:path";

function proxy(localPort, targetHost, targetPort) {
  return net
    .createServer((client) => {
      const upstream = net.connect(targetPort, targetHost);
      client.pipe(upstream);
      upstream.pipe(client);
      const close = () => {
        client.destroy();
        upstream.destroy();
      };
      client.on("error", close);
      upstream.on("error", close);
    })
    .listen(localPort, "127.0.0.1");
}

const webProxy = proxy(3000, "web", 3000);
const apiProxy = proxy(8080, "api", 8080);
const outputDir = process.env.E2E_OUTPUT_DIR ?? "./test-results";
const expectedPath = path.join(outputDir, "expected-appointment.json");
const startedAt = Date.now();
if (existsSync(expectedPath)) {
  if (process.env.E2E_REQUIRE_CLEAN_ARTIFACT === "1") {
    throw new Error(
      "Expected a clean E2E artifact volume, but a stale appointment record exists.",
    );
  }
  unlinkSync(expectedPath);
}
const playwright = spawn("corepack", ["pnpm", "exec", "playwright", "test"], {
  stdio: "inherit",
});

playwright.on("exit", (code, signal) => {
  webProxy.close();
  apiProxy.close();
  if (signal) process.kill(process.pid, signal);
  if (code === 0) {
    if (!existsSync(expectedPath)) {
      throw new Error(
        "The E2E run did not produce a persisted appointment artifact.",
      );
    }
    if (statSync(expectedPath).mtimeMs < startedAt) {
      throw new Error(
        "The E2E appointment artifact was not generated by this run.",
      );
    }
  }
  process.exit(code ?? 1);
});
